In [88]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [111]:
#!python -m pip uninstall pyqt5 --yes
#!pip3 install pyqt5==5.12.0 --user

#!pip install mibexx-gym-minesweeper --user
!pip install -e ./mibexx_gym/ 

#!pip install keras --user
#!pip install tensorflow --user

#!python -m pip uninstall keras-rl2 --yes
#!pip install keras-rl2 --user

#!pip list

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Obtaining file:///C:/Users/Yichun/Documents/UVic/2021%20Spring/SENG474/project/codes/mibexx_gym
  Found existing installation: mibexx-gym-minesweeper 0.0.3
    Uninstalling mibexx-gym-minesweeper-0.0.3:
      Successfully uninstalled mibexx-gym-minesweeper-0.0.3
  Running setup.py develop for mibexx-gym-minesweeper


In [113]:
import numpy as np
import gym

env = gym.make('mibexx_gym_minesweeper:mibexx-gym-minesweeper-v0')

env.reset()
done = False

# TEST

print("Observation space: ", env.observation_space.shape)
print("Action space: ", env.action_space.nvec)


state, reward, done, _ = env.step((0, 0))
print(f"Reward: {reward} Done: {done}")
state, reward, done, _ = env.step((0, 0))
print(f"Reward: {reward} Done: {done}")

env.render()

env.reset()
done = False

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

Observation space:  (9, 9)
Action space:  [9 9]
Reward: 0 Done: False
Reward: -1 Done: False
[[-1  1  0  0  0  0  0  0  0]
 [ 1  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [119]:
#np.random.seed(123)
#env.seed(123)

#env.action_space.nvec
#env.action_space.sample()

nb_actions = env.action_space.nvec[0] * env.action_space.nvec[1]

observation = env.reset()
for t in range(100):
        env.render()
        action = env.action_space.sample()
        (observation, reward, done, info) = env.step(action)
        print (observation, reward, done, info, action)
        print()
        if done:
            print("Finished after {} timesteps".format(t+1))
            break


[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[-1 -1 -1  1  0  1 -1  1  0]
 [ 1  1 -1  1  1  1 -1  1  0]
 [ 0  1 -1 -1 -1 -1 -1  2  0]
 [ 0  1 -1 -1 -1  1  1  2  0]
 [ 0  1  1  1 -1  1  0  0  0]
 [ 0  0  0  1 -1  2  0  0  0]
 [ 0  2  1  1 -1  1  0  0  0]
 [ 1  1 -1 -1 -1  1  1  2  0]
 [-1 -1 -1 -1 -1 -1 -1  1  0]] 0 False {} [5 4]

[[-1 -1 -1  1  0  1 -1  1  0]
 [ 1  1 -1  1  1  1 -1  1  0]
 [ 0  1 -1 -1 -1 -1 -1  2  0]
 [ 0  1 -1 -1 -1  1  1  2  0]
 [ 0  1  1  1 -1  1  0  0  0]
 [ 0  0  0  1 -1  2  0  0  0]
 [ 0  2  1  1 -1  1  0  0  0]
 [ 1  1 -1 -1 -1  1  1  2  0]
 [-1 -1 -1 -1 -1 -1 -1  1  0]]
[[-1 -1 -1  1  0  1 -1  1  0]
 [ 1  1 -1  1  1  1 -1  1  0]
 [ 0  1 -1 -1 -1 -1 -1  2  0]
 [ 0  1 -1 -1 -1  1  1  2  0]
 [ 0  1  1  1 -1  1  0  0  0]
 [ 0  0  0  1 -1  2  0  0  0]
 [ 0  2  1  1 -1  1  0  0  0]
 [ 1  1 -1 -1 -1  1  1  2  0]
 [-1 -1 -1

In [120]:

import keras

from keras.models import *
from keras.layers import *
from keras.optimizers import Adam

from rl.agents.dqn import DQNAgent 
from rl.policy import EpsGreedyQPolicy
from rl.memory import SequentialMemory
#from tensorflow.keras.models import Sequential

In [121]:
def nn_model():
    model = Sequential()
    model.add(Flatten(input_shape=(1,) + env.observation_space.shape))
    model.add(Dense(50))
    model.add(Activation('relu'))
    model.add(Dense(50))
    model.add(Activation('relu'))
    model.add(Dense(50))
    model.add(Activation('relu'))
    model.add(Dense(81))
    
    return model

In [122]:
model = nn_model()
model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_14 (Flatten)         (None, 81)                0         
_________________________________________________________________
dense_53 (Dense)             (None, 50)                4100      
_________________________________________________________________
activation_39 (Activation)   (None, 50)                0         
_________________________________________________________________
dense_54 (Dense)             (None, 50)                2550      
_________________________________________________________________
activation_40 (Activation)   (None, 50)                0         
_________________________________________________________________
dense_55 (Dense)             (None, 50)                2550      
_________________________________________________________________
activation_41 (Activation)   (None, 50)              

In [124]:
policy = EpsGreedyQPolicy()
memory = SequentialMemory(limit=50000, window_length=1)
dqn = DQNAgent(
               model=model,
               nb_actions = 81, 
               memory=memory, 
               nb_steps_warmup=100, 
               target_model_update=1e-3, 
               policy=policy,
               enable_double_dqn=True,
              )
dqn.compile(Adam(lr=1e-4), metrics=['mae'])
 
history = dqn.fit(env, nb_steps = 1000)

Training for 1000 steps ...
Interval 1 (0 steps performed)


TypeError: 'numpy.int64' object is not iterable

5